/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tls.liferaylms.mail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MailTemplate service. Represents a row in the &quot;lmsmail_MailTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tls.liferaylms.mail.model.impl.MailTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tls.liferaylms.mail.model.impl.MailTemplateImpl}.
 * </p>
 *
 * @author je03042
 * @see MailTemplate
 * @see com.tls.liferaylms.mail.model.impl.MailTemplateImpl
 * @see com.tls.liferaylms.mail.model.impl.MailTemplateModelImpl
 * @generated
 */
public interface MailTemplateModel extends BaseModel<MailTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mail template model instance should use the {@link MailTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this mail template.
	 *
	 * @return the primary key of this mail template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mail template.
	 *
	 * @param primaryKey the primary key of this mail template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this mail template.
	 *
	 * @return the uuid of this mail template
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this mail template.
	 *
	 * @param uuid the uuid of this mail template
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id template of this mail template.
	 *
	 * @return the id template of this mail template
	 */
	public long getIdTemplate();

	/**
	 * Sets the id template of this mail template.
	 *
	 * @param idTemplate the id template of this mail template
	 */
	public void setIdTemplate(long idTemplate);

	/**
	 * Returns the company ID of this mail template.
	 *
	 * @return the company ID of this mail template
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this mail template.
	 *
	 * @param companyId the company ID of this mail template
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this mail template.
	 *
	 * @return the group ID of this mail template
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this mail template.
	 *
	 * @param groupId the group ID of this mail template
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this mail template.
	 *
	 * @return the user ID of this mail template
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this mail template.
	 *
	 * @param userId the user ID of this mail template
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mail template.
	 *
	 * @return the user uuid of this mail template
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this mail template.
	 *
	 * @param userUuid the user uuid of this mail template
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the subject of this mail template.
	 *
	 * @return the subject of this mail template
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this mail template.
	 *
	 * @param subject the subject of this mail template
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this mail template.
	 *
	 * @return the body of this mail template
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this mail template.
	 *
	 * @param body the body of this mail template
	 */
	public void setBody(String body);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MailTemplate mailTemplate);

	public int hashCode();

	public CacheModel<MailTemplate> toCacheModel();

	public MailTemplate toEscapedModel();

	public String toString();

	public String toXmlString();
}