/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.lti.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LtiItem service. Represents a row in the &quot;lti_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.lti.model.impl.LtiItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.lti.model.impl.LtiItemImpl}.
 * </p>
 *
 * @author Diego Renedo Delgado
 * @see LtiItem
 * @see com.liferay.lms.lti.model.impl.LtiItemImpl
 * @see com.liferay.lms.lti.model.impl.LtiItemModelImpl
 * @generated
 */
public interface LtiItemModel extends BaseModel<LtiItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lti item model instance should use the {@link LtiItem} interface instead.
	 */

	/**
	 * Returns the primary key of this lti item.
	 *
	 * @return the primary key of this lti item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lti item.
	 *
	 * @param primaryKey the primary key of this lti item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lti item.
	 *
	 * @return the uuid of this lti item
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this lti item.
	 *
	 * @param uuid the uuid of this lti item
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the lti item ID of this lti item.
	 *
	 * @return the lti item ID of this lti item
	 */
	public long getLtiItemId();

	/**
	 * Sets the lti item ID of this lti item.
	 *
	 * @param ltiItemId the lti item ID of this lti item
	 */
	public void setLtiItemId(long ltiItemId);

	/**
	 * Returns the act ID of this lti item.
	 *
	 * @return the act ID of this lti item
	 */
	public long getActId();

	/**
	 * Sets the act ID of this lti item.
	 *
	 * @param actId the act ID of this lti item
	 */
	public void setActId(long actId);

	/**
	 * Returns the company ID of this lti item.
	 *
	 * @return the company ID of this lti item
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this lti item.
	 *
	 * @param companyId the company ID of this lti item
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this lti item.
	 *
	 * @return the group ID of this lti item
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lti item.
	 *
	 * @param groupId the group ID of this lti item
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this lti item.
	 *
	 * @return the create date of this lti item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lti item.
	 *
	 * @param createDate the create date of this lti item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this lti item.
	 *
	 * @return the user ID of this lti item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lti item.
	 *
	 * @param userId the user ID of this lti item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lti item.
	 *
	 * @return the user uuid of this lti item
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this lti item.
	 *
	 * @param userUuid the user uuid of this lti item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this lti item.
	 *
	 * @return the name of this lti item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lti item.
	 *
	 * @param name the name of this lti item
	 */
	public void setName(String name);

	/**
	 * Returns the description of this lti item.
	 *
	 * @return the description of this lti item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this lti item.
	 *
	 * @param description the description of this lti item
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this lti item.
	 *
	 * @return the url of this lti item
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this lti item.
	 *
	 * @param url the url of this lti item
	 */
	public void setUrl(String url);

	/**
	 * Returns the secret of this lti item.
	 *
	 * @return the secret of this lti item
	 */
	@AutoEscape
	public String getSecret();

	/**
	 * Sets the secret of this lti item.
	 *
	 * @param secret the secret of this lti item
	 */
	public void setSecret(String secret);

	/**
	 * Returns the rol of this lti item.
	 *
	 * @return the rol of this lti item
	 */
	@AutoEscape
	public String getRol();

	/**
	 * Sets the rol of this lti item.
	 *
	 * @param rol the rol of this lti item
	 */
	public void setRol(String rol);

	/**
	 * Returns the conten type of this lti item.
	 *
	 * @return the conten type of this lti item
	 */
	@AutoEscape
	public String getContenType();

	/**
	 * Sets the conten type of this lti item.
	 *
	 * @param contenType the conten type of this lti item
	 */
	public void setContenType(String contenType);

	/**
	 * Returns the iframe of this lti item.
	 *
	 * @return the iframe of this lti item
	 */
	public boolean getIframe();

	/**
	 * Returns <code>true</code> if this lti item is iframe.
	 *
	 * @return <code>true</code> if this lti item is iframe; <code>false</code> otherwise
	 */
	public boolean isIframe();

	/**
	 * Sets whether this lti item is iframe.
	 *
	 * @param iframe the iframe of this lti item
	 */
	public void setIframe(boolean iframe);

	/**
	 * Returns the note of this lti item.
	 *
	 * @return the note of this lti item
	 */
	public int getNote();

	/**
	 * Sets the note of this lti item.
	 *
	 * @param note the note of this lti item
	 */
	public void setNote(int note);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LtiItem ltiItem);

	public int hashCode();

	public CacheModel<LtiItem> toCacheModel();

	public LtiItem toEscapedModel();

	public String toString();

	public String toXmlString();
}