/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tls.liferaylms.mail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MailJob service. Represents a row in the &quot;lmsmail_MailJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tls.liferaylms.mail.model.impl.MailJobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tls.liferaylms.mail.model.impl.MailJobImpl}.
 * </p>
 *
 * @author je03042
 * @see MailJob
 * @see com.tls.liferaylms.mail.model.impl.MailJobImpl
 * @see com.tls.liferaylms.mail.model.impl.MailJobModelImpl
 * @generated
 */
public interface MailJobModel extends BaseModel<MailJob> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mail job model instance should use the {@link MailJob} interface instead.
	 */

	/**
	 * Returns the primary key of this mail job.
	 *
	 * @return the primary key of this mail job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mail job.
	 *
	 * @param primaryKey the primary key of this mail job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this mail job.
	 *
	 * @return the uuid of this mail job
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this mail job.
	 *
	 * @param uuid the uuid of this mail job
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the id job of this mail job.
	 *
	 * @return the id job of this mail job
	 */
	public long getIdJob();

	/**
	 * Sets the id job of this mail job.
	 *
	 * @param idJob the id job of this mail job
	 */
	public void setIdJob(long idJob);

	/**
	 * Returns the company ID of this mail job.
	 *
	 * @return the company ID of this mail job
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this mail job.
	 *
	 * @param companyId the company ID of this mail job
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this mail job.
	 *
	 * @return the group ID of this mail job
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this mail job.
	 *
	 * @param groupId the group ID of this mail job
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this mail job.
	 *
	 * @return the user ID of this mail job
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this mail job.
	 *
	 * @param userId the user ID of this mail job
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mail job.
	 *
	 * @return the user uuid of this mail job
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this mail job.
	 *
	 * @param userUuid the user uuid of this mail job
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the id template of this mail job.
	 *
	 * @return the id template of this mail job
	 */
	public long getIdTemplate();

	/**
	 * Sets the id template of this mail job.
	 *
	 * @param idTemplate the id template of this mail job
	 */
	public void setIdTemplate(long idTemplate);

	/**
	 * Returns the condition class name of this mail job.
	 *
	 * @return the condition class name of this mail job
	 */
	@AutoEscape
	public String getConditionClassName();

	/**
	 * Sets the condition class name of this mail job.
	 *
	 * @param conditionClassName the condition class name of this mail job
	 */
	public void setConditionClassName(String conditionClassName);

	/**
	 * Returns the condition class p k of this mail job.
	 *
	 * @return the condition class p k of this mail job
	 */
	public long getConditionClassPK();

	/**
	 * Sets the condition class p k of this mail job.
	 *
	 * @param conditionClassPK the condition class p k of this mail job
	 */
	public void setConditionClassPK(long conditionClassPK);

	/**
	 * Returns the condition status of this mail job.
	 *
	 * @return the condition status of this mail job
	 */
	@AutoEscape
	public String getConditionStatus();

	/**
	 * Sets the condition status of this mail job.
	 *
	 * @param conditionStatus the condition status of this mail job
	 */
	public void setConditionStatus(String conditionStatus);

	/**
	 * Returns the date class name of this mail job.
	 *
	 * @return the date class name of this mail job
	 */
	@AutoEscape
	public String getDateClassName();

	/**
	 * Sets the date class name of this mail job.
	 *
	 * @param dateClassName the date class name of this mail job
	 */
	public void setDateClassName(String dateClassName);

	/**
	 * Returns the date class p k of this mail job.
	 *
	 * @return the date class p k of this mail job
	 */
	public long getDateClassPK();

	/**
	 * Sets the date class p k of this mail job.
	 *
	 * @param dateClassPK the date class p k of this mail job
	 */
	public void setDateClassPK(long dateClassPK);

	/**
	 * Returns the date reference date of this mail job.
	 *
	 * @return the date reference date of this mail job
	 */
	public long getDateReferenceDate();

	/**
	 * Sets the date reference date of this mail job.
	 *
	 * @param dateReferenceDate the date reference date of this mail job
	 */
	public void setDateReferenceDate(long dateReferenceDate);

	/**
	 * Returns the date shift of this mail job.
	 *
	 * @return the date shift of this mail job
	 */
	public long getDateShift();

	/**
	 * Sets the date shift of this mail job.
	 *
	 * @param dateShift the date shift of this mail job
	 */
	public void setDateShift(long dateShift);

	/**
	 * Returns the team ID of this mail job.
	 *
	 * @return the team ID of this mail job
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this mail job.
	 *
	 * @param teamId the team ID of this mail job
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the processed of this mail job.
	 *
	 * @return the processed of this mail job
	 */
	public boolean getProcessed();

	/**
	 * Returns <code>true</code> if this mail job is processed.
	 *
	 * @return <code>true</code> if this mail job is processed; <code>false</code> otherwise
	 */
	public boolean isProcessed();

	/**
	 * Sets whether this mail job is processed.
	 *
	 * @param processed the processed of this mail job
	 */
	public void setProcessed(boolean processed);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MailJob mailJob);

	public int hashCode();

	public CacheModel<MailJob> toCacheModel();

	public MailJob toEscapedModel();

	public String toString();

	public String toXmlString();
}