/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tls.liferaylms.mail.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.tls.liferaylms.mail.model.MailTemplate;
import com.tls.liferaylms.mail.service.AuditSendMailsLocalService;
import com.tls.liferaylms.mail.service.AuditSendMailsService;
import com.tls.liferaylms.mail.service.MailJobLocalService;
import com.tls.liferaylms.mail.service.MailTemplateLocalService;
import com.tls.liferaylms.mail.service.MailTemplateService;
import com.tls.liferaylms.mail.service.persistence.AuditSendMailsPersistence;
import com.tls.liferaylms.mail.service.persistence.MailJobPersistence;
import com.tls.liferaylms.mail.service.persistence.MailTemplatePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the mail template local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.tls.liferaylms.mail.service.impl.MailTemplateLocalServiceImpl}.
 * </p>
 *
 * @author je03042
 * @see com.tls.liferaylms.mail.service.impl.MailTemplateLocalServiceImpl
 * @see com.tls.liferaylms.mail.service.MailTemplateLocalServiceUtil
 * @generated
 */
public abstract class MailTemplateLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MailTemplateLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.tls.liferaylms.mail.service.MailTemplateLocalServiceUtil} to access the mail template local service.
	 */

	/**
	 * Adds the mail template to the database. Also notifies the appropriate model listeners.
	 *
	 * @param mailTemplate the mail template
	 * @return the mail template that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MailTemplate addMailTemplate(MailTemplate mailTemplate)
		throws SystemException {
		mailTemplate.setNew(true);

		return mailTemplatePersistence.update(mailTemplate, false);
	}

	/**
	 * Creates a new mail template with the primary key. Does not add the mail template to the database.
	 *
	 * @param idTemplate the primary key for the new mail template
	 * @return the new mail template
	 */
	public MailTemplate createMailTemplate(long idTemplate) {
		return mailTemplatePersistence.create(idTemplate);
	}

	/**
	 * Deletes the mail template with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param idTemplate the primary key of the mail template
	 * @return the mail template that was removed
	 * @throws PortalException if a mail template with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public MailTemplate deleteMailTemplate(long idTemplate)
		throws PortalException, SystemException {
		return mailTemplatePersistence.remove(idTemplate);
	}

	/**
	 * Deletes the mail template from the database. Also notifies the appropriate model listeners.
	 *
	 * @param mailTemplate the mail template
	 * @return the mail template that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public MailTemplate deleteMailTemplate(MailTemplate mailTemplate)
		throws SystemException {
		return mailTemplatePersistence.remove(mailTemplate);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MailTemplate.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return mailTemplatePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return mailTemplatePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return mailTemplatePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return mailTemplatePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public MailTemplate fetchMailTemplate(long idTemplate)
		throws SystemException {
		return mailTemplatePersistence.fetchByPrimaryKey(idTemplate);
	}

	/**
	 * Returns the mail template with the primary key.
	 *
	 * @param idTemplate the primary key of the mail template
	 * @return the mail template
	 * @throws PortalException if a mail template with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public MailTemplate getMailTemplate(long idTemplate)
		throws PortalException, SystemException {
		return mailTemplatePersistence.findByPrimaryKey(idTemplate);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return mailTemplatePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the mail template with the UUID in the group.
	 *
	 * @param uuid the UUID of mail template
	 * @param groupId the group id of the mail template
	 * @return the mail template
	 * @throws PortalException if a mail template with the UUID in the group could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public MailTemplate getMailTemplateByUuidAndGroupId(String uuid,
		long groupId) throws PortalException, SystemException {
		return mailTemplatePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the mail templates.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of mail templates
	 * @param end the upper bound of the range of mail templates (not inclusive)
	 * @return the range of mail templates
	 * @throws SystemException if a system exception occurred
	 */
	public List<MailTemplate> getMailTemplates(int start, int end)
		throws SystemException {
		return mailTemplatePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of mail templates.
	 *
	 * @return the number of mail templates
	 * @throws SystemException if a system exception occurred
	 */
	public int getMailTemplatesCount() throws SystemException {
		return mailTemplatePersistence.countAll();
	}

	/**
	 * Updates the mail template in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param mailTemplate the mail template
	 * @return the mail template that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MailTemplate updateMailTemplate(MailTemplate mailTemplate)
		throws SystemException {
		return updateMailTemplate(mailTemplate, true);
	}

	/**
	 * Updates the mail template in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param mailTemplate the mail template
	 * @param merge whether to merge the mail template with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the mail template that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MailTemplate updateMailTemplate(MailTemplate mailTemplate,
		boolean merge) throws SystemException {
		mailTemplate.setNew(false);

		return mailTemplatePersistence.update(mailTemplate, merge);
	}

	/**
	 * Returns the audit send mails local service.
	 *
	 * @return the audit send mails local service
	 */
	public AuditSendMailsLocalService getAuditSendMailsLocalService() {
		return auditSendMailsLocalService;
	}

	/**
	 * Sets the audit send mails local service.
	 *
	 * @param auditSendMailsLocalService the audit send mails local service
	 */
	public void setAuditSendMailsLocalService(
		AuditSendMailsLocalService auditSendMailsLocalService) {
		this.auditSendMailsLocalService = auditSendMailsLocalService;
	}

	/**
	 * Returns the audit send mails remote service.
	 *
	 * @return the audit send mails remote service
	 */
	public AuditSendMailsService getAuditSendMailsService() {
		return auditSendMailsService;
	}

	/**
	 * Sets the audit send mails remote service.
	 *
	 * @param auditSendMailsService the audit send mails remote service
	 */
	public void setAuditSendMailsService(
		AuditSendMailsService auditSendMailsService) {
		this.auditSendMailsService = auditSendMailsService;
	}

	/**
	 * Returns the audit send mails persistence.
	 *
	 * @return the audit send mails persistence
	 */
	public AuditSendMailsPersistence getAuditSendMailsPersistence() {
		return auditSendMailsPersistence;
	}

	/**
	 * Sets the audit send mails persistence.
	 *
	 * @param auditSendMailsPersistence the audit send mails persistence
	 */
	public void setAuditSendMailsPersistence(
		AuditSendMailsPersistence auditSendMailsPersistence) {
		this.auditSendMailsPersistence = auditSendMailsPersistence;
	}

	/**
	 * Returns the mail job local service.
	 *
	 * @return the mail job local service
	 */
	public MailJobLocalService getMailJobLocalService() {
		return mailJobLocalService;
	}

	/**
	 * Sets the mail job local service.
	 *
	 * @param mailJobLocalService the mail job local service
	 */
	public void setMailJobLocalService(MailJobLocalService mailJobLocalService) {
		this.mailJobLocalService = mailJobLocalService;
	}

	/**
	 * Returns the mail job persistence.
	 *
	 * @return the mail job persistence
	 */
	public MailJobPersistence getMailJobPersistence() {
		return mailJobPersistence;
	}

	/**
	 * Sets the mail job persistence.
	 *
	 * @param mailJobPersistence the mail job persistence
	 */
	public void setMailJobPersistence(MailJobPersistence mailJobPersistence) {
		this.mailJobPersistence = mailJobPersistence;
	}

	/**
	 * Returns the mail template local service.
	 *
	 * @return the mail template local service
	 */
	public MailTemplateLocalService getMailTemplateLocalService() {
		return mailTemplateLocalService;
	}

	/**
	 * Sets the mail template local service.
	 *
	 * @param mailTemplateLocalService the mail template local service
	 */
	public void setMailTemplateLocalService(
		MailTemplateLocalService mailTemplateLocalService) {
		this.mailTemplateLocalService = mailTemplateLocalService;
	}

	/**
	 * Returns the mail template remote service.
	 *
	 * @return the mail template remote service
	 */
	public MailTemplateService getMailTemplateService() {
		return mailTemplateService;
	}

	/**
	 * Sets the mail template remote service.
	 *
	 * @param mailTemplateService the mail template remote service
	 */
	public void setMailTemplateService(MailTemplateService mailTemplateService) {
		this.mailTemplateService = mailTemplateService;
	}

	/**
	 * Returns the mail template persistence.
	 *
	 * @return the mail template persistence
	 */
	public MailTemplatePersistence getMailTemplatePersistence() {
		return mailTemplatePersistence;
	}

	/**
	 * Sets the mail template persistence.
	 *
	 * @param mailTemplatePersistence the mail template persistence
	 */
	public void setMailTemplatePersistence(
		MailTemplatePersistence mailTemplatePersistence) {
		this.mailTemplatePersistence = mailTemplatePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.tls.liferaylms.mail.model.MailTemplate",
			mailTemplateLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.tls.liferaylms.mail.model.MailTemplate");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return MailTemplate.class;
	}

	protected String getModelClassName() {
		return MailTemplate.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = mailTemplatePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AuditSendMailsLocalService.class)
	protected AuditSendMailsLocalService auditSendMailsLocalService;
	@BeanReference(type = AuditSendMailsService.class)
	protected AuditSendMailsService auditSendMailsService;
	@BeanReference(type = AuditSendMailsPersistence.class)
	protected AuditSendMailsPersistence auditSendMailsPersistence;
	@BeanReference(type = MailJobLocalService.class)
	protected MailJobLocalService mailJobLocalService;
	@BeanReference(type = MailJobPersistence.class)
	protected MailJobPersistence mailJobPersistence;
	@BeanReference(type = MailTemplateLocalService.class)
	protected MailTemplateLocalService mailTemplateLocalService;
	@BeanReference(type = MailTemplateService.class)
	protected MailTemplateService mailTemplateService;
	@BeanReference(type = MailTemplatePersistence.class)
	protected MailTemplatePersistence mailTemplatePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private MailTemplateLocalServiceClpInvoker _clpInvoker = new MailTemplateLocalServiceClpInvoker();
}