/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lmssa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LearningActivityTryDeleted service. Represents a row in the &quot;lmssa_LearningActivityTryDeleted&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lmssa.model.impl.LearningActivityTryDeletedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lmssa.model.impl.LearningActivityTryDeletedImpl}.
 * </p>
 *
 * @author TLS
 * @see LearningActivityTryDeleted
 * @see com.liferay.lmssa.model.impl.LearningActivityTryDeletedImpl
 * @see com.liferay.lmssa.model.impl.LearningActivityTryDeletedModelImpl
 * @generated
 */
public interface LearningActivityTryDeletedModel extends BaseModel<LearningActivityTryDeleted> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learning activity try deleted model instance should use the {@link LearningActivityTryDeleted} interface instead.
	 */

	/**
	 * Returns the primary key of this learning activity try deleted.
	 *
	 * @return the primary key of this learning activity try deleted
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learning activity try deleted.
	 *
	 * @param primaryKey the primary key of this learning activity try deleted
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this learning activity try deleted.
	 *
	 * @return the uuid of this learning activity try deleted
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this learning activity try deleted.
	 *
	 * @param uuid the uuid of this learning activity try deleted
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the lat del ID of this learning activity try deleted.
	 *
	 * @return the lat del ID of this learning activity try deleted
	 */
	public long getLatDelId();

	/**
	 * Sets the lat del ID of this learning activity try deleted.
	 *
	 * @param latDelId the lat del ID of this learning activity try deleted
	 */
	public void setLatDelId(long latDelId);

	/**
	 * Returns the act man audit ID of this learning activity try deleted.
	 *
	 * @return the act man audit ID of this learning activity try deleted
	 */
	public long getActManAuditId();

	/**
	 * Sets the act man audit ID of this learning activity try deleted.
	 *
	 * @param actManAuditId the act man audit ID of this learning activity try deleted
	 */
	public void setActManAuditId(long actManAuditId);

	/**
	 * Returns the lat ID of this learning activity try deleted.
	 *
	 * @return the lat ID of this learning activity try deleted
	 */
	public long getLatId();

	/**
	 * Sets the lat ID of this learning activity try deleted.
	 *
	 * @param latId the lat ID of this learning activity try deleted
	 */
	public void setLatId(long latId);

	/**
	 * Returns the act ID of this learning activity try deleted.
	 *
	 * @return the act ID of this learning activity try deleted
	 */
	public long getActId();

	/**
	 * Sets the act ID of this learning activity try deleted.
	 *
	 * @param actId the act ID of this learning activity try deleted
	 */
	public void setActId(long actId);

	/**
	 * Returns the user ID of this learning activity try deleted.
	 *
	 * @return the user ID of this learning activity try deleted
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this learning activity try deleted.
	 *
	 * @param userId the user ID of this learning activity try deleted
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this learning activity try deleted.
	 *
	 * @return the user uuid of this learning activity try deleted
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this learning activity try deleted.
	 *
	 * @param userUuid the user uuid of this learning activity try deleted
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the start date of this learning activity try deleted.
	 *
	 * @return the start date of this learning activity try deleted
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this learning activity try deleted.
	 *
	 * @param startDate the start date of this learning activity try deleted
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the result of this learning activity try deleted.
	 *
	 * @return the result of this learning activity try deleted
	 */
	public long getResult();

	/**
	 * Sets the result of this learning activity try deleted.
	 *
	 * @param result the result of this learning activity try deleted
	 */
	public void setResult(long result);

	/**
	 * Returns the end date of this learning activity try deleted.
	 *
	 * @return the end date of this learning activity try deleted
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this learning activity try deleted.
	 *
	 * @param endDate the end date of this learning activity try deleted
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the try data of this learning activity try deleted.
	 *
	 * @return the try data of this learning activity try deleted
	 */
	@AutoEscape
	public String getTryData();

	/**
	 * Sets the try data of this learning activity try deleted.
	 *
	 * @param tryData the try data of this learning activity try deleted
	 */
	public void setTryData(String tryData);

	/**
	 * Returns the try result data of this learning activity try deleted.
	 *
	 * @return the try result data of this learning activity try deleted
	 */
	@AutoEscape
	public String getTryResultData();

	/**
	 * Sets the try result data of this learning activity try deleted.
	 *
	 * @param tryResultData the try result data of this learning activity try deleted
	 */
	public void setTryResultData(String tryResultData);

	/**
	 * Returns the comments of this learning activity try deleted.
	 *
	 * @return the comments of this learning activity try deleted
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this learning activity try deleted.
	 *
	 * @param comments the comments of this learning activity try deleted
	 */
	public void setComments(String comments);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LearningActivityTryDeleted learningActivityTryDeleted);

	public int hashCode();

	public CacheModel<LearningActivityTryDeleted> toCacheModel();

	public LearningActivityTryDeleted toEscapedModel();

	public String toString();

	public String toXmlString();
}